# .github/workflows/scheduled-builds.yml
name: Trigger Site Rebuild on a CRON Schedule

on: [workflow_dispatch]
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: curl -X GET -d {} https://sathya.in/plugins/maintenance/Maintenance
